export const users = [
  {
    userCardThumbnail: "http://github.com/pauloluan.png",
    cardTitleText: "Paulo Luan",
    cardEmail: "pauloluan@jobnagringa.com.br",
    cardTag: "this is a tag",
    buttonSmallLink: { href: "http://jobnagringa.com.br" },
    buttonLabelText: "small text",
    buttonSmallSecondaryLink: { href: "http://jobnagringa.com.br" },
    buttonLabelSecondaryText: "secondary text",
  },
  {
    userCardThumbnail: "http://github.com/johndoe.png",
    cardTitleText: "John Doe",
    cardEmail: "johndoe@email.com",
    cardTag: "another tag",
    buttonSmallLink: { href: "http://example.com" },
    buttonLabelText: "Website",
    buttonSmallSecondaryLink: { href: "http://example.com/contact" },
    buttonLabelSecondaryText: "Contact",
  },
  {
    userCardThumbnail: "http://github.com/sarahsmith.png",
    cardTitleText: "Sarah Smith",
    cardEmail: "sarah.smith@email.com",
    cardTag: "web developer",
    buttonSmallLink: { href: "http://sarahsmithportfolio.com" },
    buttonLabelText: "Portfolio",
    buttonSmallSecondaryLink: { href: "http://sarahsmithresume.com" },
    buttonLabelSecondaryText: "Resume",
  },
  {
    userCardThumbnail: "http://github.com/alexanderjones.png",
    cardTitleText: "Alexander Jones",
    cardEmail: "alexander.jones@email.com",
    cardTag: "software engineer",
    buttonSmallLink: { href: "http://alexanderjones.com" },
    buttonLabelText: "website",
    buttonSmallSecondaryLink: { href: "http://linkedin.com/alexanderjones" },
    buttonLabelSecondaryText: "LinkedIn",
  },
  {
    userCardThumbnail: "http://github.com/emilybrown.png",
    cardTitleText: "Emily Brown",
    cardEmail: "emily.brown@email.com",
    cardTag: "graphic designer",
    buttonSmallLink: { href: "http://emilybrownportfolio.com" },
    buttonLabelText: "Portfolio",
    buttonSmallSecondaryLink: { href: "http://instagram.com/emilydesigns" },
    buttonLabelSecondaryText: "Instagram",
  },
  {
    userCardThumbnail: "http://github.com/michaelwilson.png",
    cardTitleText: "Michael Wilson",
    cardEmail: "michael.wilson@email.com",
    cardTag: "data analyst",
    buttonSmallLink: { href: "http://michaelwilsonresume.com" },
    buttonLabelText: "Resume",
    buttonSmallSecondaryLink: { href: "http://linkedin.com/michaelwilson" },
    buttonLabelSecondaryText: "LinkedIn",
  },
  {
    userCardThumbnail: "http://github.com/lisasmith.png",
    cardTitleText: "Lisa Smith",
    cardEmail: "lisa.smith@email.com",
    cardTag: "marketing manager",
    buttonSmallLink: { href: "http://lisasmithportfolio.com" },
    buttonLabelText: "Portfolio",
    buttonSmallSecondaryLink: { href: "http://twitter.com/lisamarketing" },
    buttonLabelSecondaryText: "Twitter",
  },
  {
    userCardThumbnail: "http://github.com/ryanmiller.png",
    cardTitleText: "Ryan Miller",
    cardEmail: "ryan.miller@email.com",
    cardTag: "sales executive",
    buttonSmallLink: { href: "http://ryanmillerwebsite.com" },
    buttonLabelText: "Website",
    buttonSmallSecondaryLink: { href: "http://linkedin.com/ryanmiller" },
    buttonLabelSecondaryText: "LinkedIn",
  },
  {
    userCardThumbnail: "http://github.com/jessicajackson.png",
    cardTitleText: "Jessica Jackson",
    cardEmail: "jessica.jackson@email.com",
    cardTag: "teacher",
    buttonSmallLink: { href: "http://jessicajacksonteaching.com" },
    buttonLabelText: "Teaching Website",
    buttonSmallSecondaryLink: { href: "http://facebook.com/jessicajackson" },
    buttonLabelSecondaryText: "Facebook",
  },
  {
    userCardThumbnail: "http://github.com/davidthompson.png",
    cardTitleText: "David Thompson",
    cardEmail: "david.thompson@email.com",
    cardTag: "product manager",
    buttonSmallLink: { href: "http://davidthompsonresume.com" },
    buttonLabelText: "Resume",
    buttonSmallSecondaryLink: { href: "http://linkedin.com/davidthompson" },
    buttonLabelSecondaryText: "LinkedIn",
  },
];

console.log(users);
